model_type: 'afnonet'

exp_dir: './experiments'
run_num: 'afnonet_pre'
max_epochs: 30
lr: 0.0001
scheduler: 'CosineAnnealingLR'
save_checkpoint: False
load_model: True
load_model_path: '/mnt/data/zhishuai/code/zmh_train/afnonet_baseline_pre_model/training_checkpoints/best_ckpt.tar'
log_to_screen: True
save_image: False

seed: 123
batch_size: 4
num_workers: 4
train_shuffle: False
test_shuffle: False
pin_memory: True
persistent_workers: True
prefetch_factor: 2

img_size: [720, 960, 32]
net_image:
  N_in_channels: 32
  N_out_channels: 32

in_channels: 32
out_channels: 32
patch_size: 8
embed_dim: 128
depth: 12
num_blocks: 16
